[phases.setup]
nixPkgs = ["php82", "composer", "php82Packages.pdo_sqlite", "php82Packages.intl"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "bash start.sh"

